;;; doentry-gen.el -- create-doentry  -*- lexical-binding: t; -*-

;; 2025-01-05 09:59:34
;; Author: plu5
;; Keywords: languages
;; URL: https://github.com/plu5/emacs-doentry.el

;; This file is not part of GNU Emacs.

;;; Commentary:
;; Generator for doentry files. To generate one:
;; M-x create-doentry
;; It will open in a buffer, the file is not actually created until
;; you save (though Emacs might create an autosave).
;; If `doentry-gen-dir' is not defined, it will be placed in pwd.

;;; Code:

(defgroup doentry-gen nil
  "doentry file generator."
  :group 'languages)

(defcustom doentry-gen-dir nil
  "Folder in which to generate doentry files.
It will also be looked at optionally to calculate the number of the
next doentry based on previous one if {n} is used in `doentry-gen-template'."
  :type 'directory
  :group 'doentry-gen)

(defcustom doentry-gen-template "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
	<key>Activity</key>
	<string>Stationary</string>
	<key>Creation Date</key>
	<date>{date}</date>
	<key>Entry Text</key>
	<string># {n}{heading}

■</string>
	<key>Starred</key>
	<false />
	<key>UUID</key>
	<string>{uuid}</string>
	<key>Creator</key>
	<dict>
		<key>Device Agent</key>
		<string>PC</string>
		<key>Generation Date</key>
		<date>{date}</date>
		<key>Host Name</key>
		<string>{host}</string>
		<key>OS Agent</key>
		<string>{os}</string>
		<key>Software Agent</key>
		<string>Emacs</string>
	</dict>
</dict>
</plist>"
  "Template that will be used for the generated doentry file.
The following special substrings will be replaced with calculated values:

{date}	Generation date in the format %FT%TZ in timezone UTC; compliant with
	the dates generated by DayOne and Journaley.
{n}     The number of the new doentry file calculated from the number
        on the previous one. If the number isn't found, there is no previous
        file, or `doentry-gen-dir' is not defined, it is replaced with 1.
        The number is matched with `doentry-gen-n-regexp'.
{heading}
        `doentry-gen-heading-format' timeformatted with `format-time-string'.
{uuid}	The generated uuid for the file, same one as used for its name.
{host}	`system-name'
{os}	`system-type' (`window-system') `operating-system-release'"
  :type 'string
  :group 'doentry-gen)

(defcustom doentry-gen-heading-format " | %F %a"
  "Format for {heading} substring to optionally use in `doentry-gen-template'.
Timeformatted with `format-time-string'."
  :type 'string
  :group 'doentry-gen)

(defcustom doentry-gen-n-regexp "# \\([0-9]+\\) |"
  "Regexp to use to find the n of the previous doentry
if {n} is used in `doentry-gen-template'.
The first match group should be the n."
  :type 'regexp
  :group 'doentry-gen)

(defun doentry-gen-uuid ()
  (upcase (string-replace "-" "" (org-id-uuid))))

(defun doentry-gen-date ()                  ; UTC
  (format-time-string "%FT%TZ" nil t))

(defun doentry-gen-host ()
  (system-name))

(defun doentry-gen-os ()
  ;; system-type and window-system are symbols so have to be converted
  ;; to string before concat
  (concat (symbol-name system-type) " (" (symbol-name window-system) ") "
          operating-system-release))

(defun doentry-gen-latest-file (path &optional match)
  "Return latest file in PATH matching MATCH.
PATH must not be nil."
  (car (sort (directory-files path 'full match t) #'file-newer-than-file-p)))

(defun doentry-gen-latest-file-contents ()
  "Do not call this function if `doentry-gen-dir' is nil."
  (let ((latest-log-path
         (doentry-gen-latest-file doentry-gen-dir ".*\\.doentry$")))
    (with-temp-buffer
      (insert-file-contents latest-log-path)
      (buffer-string))))

(defun doentry-gen-n ()
  "Return next doentry number.
Returns 1 if the previous number is not found, there is no previous
file, or `doentry-gen-dir' is nil."
  (if doentry-gen-dir
      (let ((latest-log-contents (doentry-gen-latest-file-contents)))
        (if (string-match doentry-gen-n-regexp latest-log-contents)
            (+ 1 (string-to-number (match-string 1 latest-log-contents)))
          1))
    1))

(defun doentry-gen-heading ()
  (format-time-string " | %F %a"))

(defun doentry-gen-populated-template (uuid)
  (string-replace
   "{heading}" (doentry-gen-heading)
   (string-replace
    "{os}" (doentry-gen-os)
    (string-replace
     "{host}" (doentry-gen-host)
     (string-replace
      "{date}" (doentry-gen-date)
      (string-replace
       "{uuid}" uuid
       (string-replace "{n}" (format "%05d" (doentry-gen-n))
                       doentry-gen-template)))))))

;;;###autoload
(defun create-doentry ()
  (interactive)
  (let ((uuid (doentry-gen-uuid)))
    (find-file (expand-file-name (concat uuid ".doentry") doentry-gen-dir))
    (insert (doentry-gen-populated-template uuid))
    ;; qol
    (search-backward "■")
    (previous-line)
  ))

(provide 'doentry-gen)

;;; doentry-gen ends here
